name: CI
on:
  push:
    branches: [ develop, feature/*, fatures/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Tests
      run: dotnet test --no-restore --verbosity normal
    - name: Functional Tests
      run: dotnet run -c release
      working-directory: ./test/Itinero.Optimization.Tests.Functional/
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/Itinero.Optimization/
